version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coworking_reservation_app_container
    ports:
      - "8080:8080"
    depends_on:
      - coworking_reservation_app_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://coworking_reservation_app_db:5432/coworking_reservation_app
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

  coworking_reservation_app_db:
    image: postgres:17.4
    container_name: coworking_reservation_app_db_container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - coworking_reservation_app_db:/var/lib/postgresql/data

volumes:
  coworking_reservation_app_db:



